name: Trigger Website Sync
on: [push]
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Signal to Main Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: GauravNJain/gauravnjain.github.io
          event-type: sync_content
